---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app.kubernetes.io/name: load-generator
    app.kubernetes.io/part-of: test-stand-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: load-generator
  template:
    metadata:
      annotations:
        ad.datadoghq.com/load-generator.logs: '[{"source": "demo"}]'
      labels:
        app.kubernetes.io/name: load-generator
        app.kubernetes.io/part-of: test-stand-demo
    spec:
      containers:
        - name: load-generator
          image: test-stand-load-generator:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: traced-service-env
          env:
            - name: GATEWAY_URL
              value: http://gateway-api:8080
            - name: START_DELAY
              value: "5s"
            - name: DURATION
              value: "0"
            - name: LOAD_PROFILE
              value: "__LOAD_PROFILE__"
            - name: RPS
              value: "__LOAD_RPS__"
            - name: ERROR_RATE_PCT
              value: "__LOAD_ERROR_RATE_PCT__"
            - name: MIX
              value: "__LOAD_MIX__"
